# Namespaces can help simplfy a few things with your configuration.
#
# If services are in the same namespace then the service name can be
# configured as the host name to access those services.
#
# The way DNS works inside kubernetes is, the namespace and the rest of what
# k8s needs is auto appended so you have the same configuration on all env
# just the namespace differs.
#
# Another thing a namespace does is to bundle the resources used by an namespace.
#
# Another thing is network security if you implement network security with
# network policies. It is very easy to restrict traffic between namespaces but
# by default is allowed inside the same namespace.

apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: sales
          image: sales-image

          ports:
            - name: sales
              containerPort: 3000
            - name: sales-debug
              containerPort: 3010

          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system

spec:
  selector:
    app: sales
